# Generated by Django 2.2 on 2020-10-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_imagecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomment',
            name='author',
        ),
    ]
